project:
  type: website

website:
  title: "my quarto website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: slides/slides.qmd
        text: Slides
execute:
  freeze: auto
format:
  html:
    theme:
      - cosmo
      - brand
    toc: true



